import numpy as np
print('隨機正整數：',end='')
x=np.random.randint(low=5,high=16,size=15)
print(x)
x=x.reshape(3,5)
print('X矩陣內容：')
print(x)
print('最大：',end='')
print(x.max())
print('最小：',end='')
print(x.min())
print('總和：',end='')
print(x.sum())
print('平均：',end='')
print(x.mean())
print('四個角落元素：',end='')
print(x[np.ix_([0,2],[0,4])])
np.savetxt('EX3-2.txt',x)
y=np.random.randint(low=5,high=16,size=15).reshape(3,5)
print('Y矩陣內容：')
print(y)
z=x+y
print('Z矩陣內容：')
print(z)

